on: [push, pull_request, workflow_dispatch]

name: Build
jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 17
        uses: actions/setup-node@v2
        with:
          node-version: 17.x
      - name: Install dependencies
        run: npm install
      - name: Generate unrouted PCBs
        run: node src/cli.js input/zentrik_kyria_xiao.yaml -o kicad/boards/zentrik_kyria_xiao
      - name: Export DSN for main PCB
        uses: ./.github/actions/export-dsn
        with:
          pcb_file: kicad/boards/zentrik_kyria_custom/pcbs/board.kicad_pcb
          dsn_file: kicad/boards/zentrik_kyria_custom/pcbs/board.dsn
      - name: Autoroute main PCB
        uses: ./.github/actions/autoroute
        with:
          dsn_file: kicad/boards/zentrik_kyria_custom/pcbs/board.dsn
          ses_file: kicad/boards/zentrik_kyria_custom/pcbs/board.ses
      - name: Import SES into main PCB
        uses: ./.github/actions/import-ses
        with:
          pcb_input_file: kicad/boards/zentrik_kyria_custom/pcbs/board.kicad_pcb
          pcb_output_file: kicad/boards/zentrik_kyria_custom/pcbs/board_routed.kicad_pcb
          ses_file: kicad/boards/zentrik_kyria_custom/pcbs/board.ses
      - name: Export Gerbers for top plate
        uses: ./.github/actions/export-gerbers
        with:
          pcb_file: kicad/boards/zentrik_kyria_custom/pcbs/top_plate.kicad_pcb
          gerbers_dir: kicad/boards/zentrik_kyria_custom/gerbers/top_plate
      - name: Export Gerbers for bottom plate
        uses: ./.github/actions/export-gerbers
        with:
          pcb_file: kicad/boards/zentrik_kyria_custom/pcbs/bottom_plate.kicad_pcb
          gerbers_dir: kicad/boards/zentrik_kyria_custom/gerbers/bottom_plate
      - name: Export Gerbers for main PCB
        uses: ./.github/actions/export-gerbers
        with:
          pcb_file: kicad/boards/zentrik_kyria_custom/pcbs/board.kicad_pcb
          gerbers_dir: kicad/boards/zentrik_kyria_custom/gerbers/board
      - name: Persist output
        uses: actions/upload-artifact@v2
        with:
          name: zentrik-routed-pcbs-and-gerbers
          path: kicad/boards/zentrik_kyria_custom
